postgresql:
    image: postgres:9.5
    ports:
        - "5432:5432"
    environment:
        - POSTGRES_USER=hive
        - POSTGRESS_PASSWORD=password
        - POSTGRES_DB=metastore

hdfs-namenode:
    image: uhopper/hadoop-namenode:2.7.2
    ports:
      - "8020:8020"
      - "50070:50070"
    environment:
      - CLUSTER_NAME=hadoop

metastore:
    image: mozdata/docker-hive-metastore:1.2.1
    ports:
      - "9083:9083"
    links:
      - postgresql
      - hdfs-namenode
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://hdfs-namenode:8020
      - DB_URI=postgresql
      - DB_USER=hive
      - DB_PASSWORD=password

presto:
    build: ..
    links:
      - metastore
      - hdfs-namenode
    ports:
      - "8080:8080"
    environment:
      - CONFIG_CONF_QUERY_MAX___MEMORY=256MB
      - CONFIG_CONF_QUERY_MAX___MEMORY___PER___NODE=256MB
      - JVM_CONF_XMX=512M
      - HIVE_CONF_HIVE_METASTORE_URI=thrift://metastore:9083
